/** 
    NOTE: THIS IS ONLY FOR THE INITIAL DATABASE SETUP FOR BUDGET_DB WHICH REQUIRES USING MASTER, 
    DO OTHER UPDATES IN THE LIQUBIASE FOLDER!!!! 
**/

USE [master]
GO

/****** Object:  Database [BUDGET_DB]    Script Date: 3/31/2020 7:16:49 PM ******/
CREATE DATABASE [BUDGET_DB]
GO
ALTER DATABASE [BUDGET_DB] SET COMPATIBILITY_LEVEL = 140
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [BUDGET_DB].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [BUDGET_DB] SET ANSI_NULL_DEFAULT ON 
GO
ALTER DATABASE [BUDGET_DB] SET ANSI_NULLS ON 
GO
ALTER DATABASE [BUDGET_DB] SET ANSI_PADDING ON 
GO
ALTER DATABASE [BUDGET_DB] SET ANSI_WARNINGS ON 
GO
ALTER DATABASE [BUDGET_DB] SET ARITHABORT ON 
GO
ALTER DATABASE [BUDGET_DB] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [BUDGET_DB] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [BUDGET_DB] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [BUDGET_DB] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [BUDGET_DB] SET CURSOR_DEFAULT  LOCAL 
GO
ALTER DATABASE [BUDGET_DB] SET CONCAT_NULL_YIELDS_NULL ON 
GO
ALTER DATABASE [BUDGET_DB] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [BUDGET_DB] SET QUOTED_IDENTIFIER ON 
GO
ALTER DATABASE [BUDGET_DB] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [BUDGET_DB] SET  DISABLE_BROKER 
GO
ALTER DATABASE [BUDGET_DB] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [BUDGET_DB] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [BUDGET_DB] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [BUDGET_DB] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [BUDGET_DB] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [BUDGET_DB] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [BUDGET_DB] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [BUDGET_DB] SET RECOVERY FULL 
GO
ALTER DATABASE [BUDGET_DB] SET  MULTI_USER 
GO
ALTER DATABASE [BUDGET_DB] SET PAGE_VERIFY NONE  
GO
ALTER DATABASE [BUDGET_DB] SET DB_CHAINING OFF 
GO
ALTER DATABASE [BUDGET_DB] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [BUDGET_DB] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO
ALTER DATABASE [BUDGET_DB] SET DELAYED_DURABILITY = DISABLED 
GO
EXEC sys.sp_db_vardecimal_storage_format N'BUDGET_DB', N'ON'
GO
ALTER DATABASE [BUDGET_DB] SET QUERY_STORE = OFF
GO