// SYSTEM SETTINGS ACTION TYPES
export const ADD_SYSTEMSETTINGS = "ADD_SYSTEMSETTINGS";
export const UPDATE_SYSTEMSETTINGS = "UPDATE_SYSTEMSETTINGS";
export const UPDATE_SYSTEMSETTINGSDB = "UPDATE_SYSTEMSETTINGSDB";
export const FETCH_SYSTEMSETTINGS = "FETCH_SYSTEMSETTINGS";
// STRUCTURE TABLES ACTION TYPES
export const ADD_STRUCTURETABLES = "ADD_STRUCTURETABLES";
export const UPDATE_STRUCTURETABLES = "UPDATE_STRUCTURETABLES";
export const FETCH_STRUCTURETABLES = "FETCH_STRUCTURETABLES";
export const FETCH_FTE_DIVISORS = "FETCH_FTE_DIVISORS";
// BUDGET VERSIONS ACTION TYPES
export const ADD_BUDGETVERSIONS = "ADD_BUDGETVERSIONS";
export const DELETE_BUDGETVERSIONS = "DELETE_BUDGETVERSIONS";
export const UPDATE_BUDGETVERSIONS = "UPDATE_BUDGETVERSIONS";
export const FETCH_BUDGETVERSIONS = "FETCH_BUDGETVERSIONS";
export const CHANGE_BUDGETVERSIONS = "CHANGE_BUDGETVERSIONS";
export const RENAME_BUDGETVERSIONS = "RENAME_BUDGETVERSIONS";
export const COPY_BUDGETVERSIONS = "COPY_BUDGETVERSIONS";
export const RESET_BUDGETVERSIONS = "RESET_BUDGETVERSIONS";
export const ADD_ALL_BUDGETVERSIONS_FILTERS = "ADD_ALL_BUDGETVERSIONS_FILTERS";
export const ADD_BUDGETVERSIONS_FILTER = "ADD_BUDGETVERSIONS_FILTER";
export const ADD_BUDGETVERSIONS_FILTER_GROUP = "ADD_BUDGETVERSIONS_FILTER_GROUP";
export const REMOVE_ALL_BUDGETVERSIONS_FILTERS = "REMOVE_ALL_BUDGETVERSIONS_FILTERS";
export const REMOVE_ALL_BUDGETVERSIONS_FILTER_GROUP = "REMOVE_ALL_BUDGETVERSIONS_FILTER_GROUP";
export const REMOVE_BUDGETVERSIONS_FILTER = "REMOVE_BUDGETVERSIONS_FILTER";
export const REMOVE_BUDGETVERSIONS_FILTER_GROUP = "REMOVE_BUDGETVERSIONS_FILTER_GROUP";
export const RESET_BUDGETVERSIONS_FILTERS = "RESET_BUDGETVERSIONS_FILTERS";
export const SET_BUDGETVERSIONS_FILTER_OPTIONS = "SET_BUDGETVERSIONS_FILTER_OPTIONS";
export const SET_BUDGETVERSIONS_FILTERED_FLAG = "SET_BUDGETVERSIONS_FILTERED_FLAG";
export const SET_BUDGETVERSIONS_SORT_DIRECTION = "SET_BUDGETVERSIONS_SORT_DIRECTION";
export const SET_BUDGETVERSIONS_SORT_FACTOR = "SET_BUDGETVERSIONS_SORT_FACTOR";
export const SET_BUDGETVERSIONS_SORTED_FLAG = "SET_BUDGETVERSIONS_SORTED_FLAG";

// ITEM TYPES ACTIONS TYPES
export const ADD_ITEMTYPES = "ADD_ITEMTYPES";
export const DELETE_ITEMTYPES = "DELETE_ITEMTYPES";
export const FETCH_ITEMTYPES = "FETCH_ITEMTYPES";
export const UPDATE_ITEMTYPES = "UPDATE_ITEMTYPES";
export const UPDATE_ITEMTYPESDB = "UPDATE_ITEMTYPESDB";
// Notification DATA ACTIONS TYPES
export const FETCH_NOTIFICATIONS = "FETCH_NOTIFICATIONS";
export const MARK_NOTIFICATIONS = "MARK_NOTIFICATIONS";

// MASTER DATA ACTIONS TYPES
export const FETCH_BUDGETTYPE = "FETCH_BUDGETTYPE";
export const FETCH_BUDGETVERSIONTYPE = "FETCH_BUDGETVERSIONTYPE";
export const FETCH_FORECASTMETHODTYPE = "FETCH_FORECASTMETHODTYPE";
export const FETCH_SCENARIOTYPE = "FETCH_SCENARIOTYPE";
export const FETCH_ITEMDATEFORMAT = "FETCH_ITEMDATEFORMAT";
export const FETCH_ITEMDECIMALPLACES = "FETCH_ITEMDECIMALPLACES";
export const FETCH_ITEMMONTHS = "FETCH_ITEMMONTHS";
export const FETCH_FISCALYEAR = "FETCH_FISCALYEAR";
export const REMOVE_MASTER_DATA = "REMOVE_MASTER_DATA";
// Dimensions Data Action Type
export const FETCH_ENTITIES = "FETCH_ENTITIES";
export const FETCH_DEPARTMENTS = "FETCH_DEPARTMENTS";
export const FETCH_STATISTICS = "FETCH_STATISTICS";
export const FETCH_DIMENSION_RELATIONSHIPS = "FETCH_DIMENSION_RELATIONSHIPS";
export const FETCH_GLACCOUNTS = "FETCH_GLACCOUNTS";
export const FETCH_PAYTYPES = "FETCH_PAYTYPES";
export const FETCH_JOBCODES = "FETCH_JOBCODES";
export const FETCH_DEPARTMENT_RELATIONSHIPS = "FETCH_DEPARTMENT_RELATIONSHIPS";
export const FETCH_GLACCOUNTS_RELATIONSHIPS = "FETCH_GLACCOUNTS_RELATIONSHIPS";


//TimePeriods Action Type
export const FETCH_TIMEPERIODS = "FETCH_TIMEPERIODS";

// FORECAST ACTION TYPES
export const UPDATE_FORECAST = "UPDATE_FORECAST";
export const REFRESH_FORECAST = "REFRESH_FORECAST";


// MAPPING ACTION TYPES
export const UPDATE_MAPPING = "UPDATE_MAPPING";
export const REFRESH_MAPPING = "REFRESH_MAPPING";

// Pay type distributions Aciton types
export const FETCH_PAYTYPEDISTRIBUTIONS = "FETCH_PAYTYPEDISTRIBUTIONS";


// STAFFINGDATATYPE
export const FETCH_STAFFINGDATATYPE = "FETCH_STAFFINGDATATYPE";

//SAVEUSERDETAILS
export const SAVE_USER_DETAILS = 'SAVE_USER_DETAILS';